spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easypeacyrecipes?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    enabled: true

logging:
  level:
    org:
      springframework: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8081

jwt:
  secret: ${JWT_KEY}

